site_name: Google Cloud Gemini
site_url: https://example.com
site_description: Google Cloud Gemini
site_author: Sampath Kumar

# Repository
repo_name: demo
repo_url: https://github.com/msampathkumar/mkdocs

# Copyright
copyright: Copyright Sampath Kumar 2025
theme:
  icon:
    logo: fontawesome/solid/water
  # favicon: assets/favicon.png
  # logo: assets/logo.svg
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.top
    # - navigation.tabs
    # - search
    - navigation.indexes # for blog/index.md
markdown_extensions:
  - attr_list
  # emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # code blocks
  # https://jameswillett.dev/getting-started-with-material-for-mkdocs/?h=emoji#code-blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # convert simple urls to markdown link
  - pymdownx.magiclink
# navigation
nav:
  - Home: index.md
  - Multilevel pages:
    - multilevel/default.md
    - Page 1: multilevel/page1.md
    - Page 2: multilevel/page2.md
  - Thanks: Thanks.md
  - Blog:
    - blog/index.md

# for blogging
plugins:
  - search
  - blog